import { CommissionLedger } from "@/components/commissions/commission-ledger";
import { DashboardDateRangeFilter } from "@/components/dashboard/date-range-filter";
import type { RecordFiltersState } from "@/components/filters/record-filters";
import { SidebarShell } from "@/components/layout/sidebar-shell";
import { requirePartner } from "@/lib/auth/current-user";
import { getPartnerCommissionLedger, type CommissionLedgerScope } from "@/lib/commissions/queries";
import { groupLeaderNav, managerNav, partnerNav } from "@/lib/constants/navigation";
import { parseDashboardDateRange } from "@/lib/dashboard/date-range";

function navigationForRole(role: string) {
  if (role === "MANAGER") return managerNav;
  if (role === "GROUP_LEADER") return groupLeaderNav;
  return partnerNav;
}

function scopeForRole(role: string): CommissionLedgerScope {
  if (role === "MANAGER") return "manager";
  if (role === "GROUP_LEADER") return "group_leader";
  return "partner";
}

function copyForScope(scope: CommissionLedgerScope) {
  if (scope === "manager") {
    return {
      eyebrow: "Manager",
      title: "Manager commissions",
      description: "Track personal manager earnings plus the commission activity generated by your assigned team."
    };
  }

  if (scope === "group_leader") {
    return {
      eyebrow: "Group leader",
      title: "Leader commissions",
      description: "Track your personal leader earnings and the agent commissions connected to your team."
    };
  }

  return {
    eyebrow: "Partner",
    title: "Partner commission ledger",
    description: "Review your partner profit, team payout obligations, and commission statuses for the network assigned to you."
  };
}

export default async function PartnerCommissionsPage({ searchParams }: { searchParams: Promise<RecordFiltersState> }) {
  const filters = await searchParams;
  const dateRange = parseDashboardDateRange(filters);
  const user = await requirePartner();
  const scope = scopeForRole(user.role);
  const copy = copyForScope(scope);
  const entries = await getPartnerCommissionLedger(user, dateRange);

  return (
    <SidebarShell nav={navigationForRole(user.role)} eyebrow={copy.eyebrow} title="Commissions">
      <DashboardDateRangeFilter range={dateRange} resetHref="/partner/commissions" hiddenParams={{ q: filters.q ?? "", status: filters.status ?? "ALL", role: filters.role ?? "ALL" }} />
      <CommissionLedger entries={entries} scope={scope} title={copy.title} description={copy.description} filters={filters} dateRangeLabel={dateRange.label} />
    </SidebarShell>
  );
}
